FROM node:18.12.1-alpine AS builder

ENV NODE_ENV staging

ENV NODE_OPTIONS=--openssl-legacy-provider

# Add a work directory
WORKDIR /app

COPY package*.json ./

# Copy app files
COPY . .

# yarn build
#COPY yarn.lock .
#RUN yarn install

# npm build
RUN npm ci

#build
RUN npm run build

# yarn build
#RUN yarn build




# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV staging

# Copy built assets from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Add your nginx.conf
COPY deployment/kubernetes/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]